workspace:
        base: /go
        path: src/github.com/f6systems/bsdo

pipeline:
        build:
         image: golang
         commands:
                - make bsdo

services:
  mysql:
    image: wiq-mysql
